[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ngcore"
version = "0.1.0"
description = "Dynamic AI Skill Orchestration Framework"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

authors = [
    {name = "Ganesh Naidu"}
]

keywords = [
    "ai",
    "llm",
    "prompt",
    "prompt-engineering",
    "workflow",
    "skills"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]